version: '3.7'

services:

  frontend:
    container_name: frontend 
    build:
      context: ./react-markdowner
      dockerfile: Dockerfile
    volumes:
      - './react-markdowner:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development

